### ISSUE TITLE
[TicTacToe] Красивенько, хорошо

### ISSUE THREAD

**Issue by pavel-b-novikov** [IlyaTolstihin/nsudotnet#1]
Только игра заканчивается когда-нибудь, нет?

**Comment by IlyaTolstihin** [comment]
Нет, пока есть свободные батоны. Она должна заканчиваться?

**Comment by pavel-b-novikov** [comment]
Ну а обычные крестики-нолики в какой момент заканчиваются?

**Comment by IlyaTolstihin** [comment]
Я исправил логику, теперь игра заканчивается так же, как в обычных крестиках-ноликах

**Comment by pavel-b-novikov** [comment]
ок, ладно
