### ISSUE TITLE
[TicTacToe] Image Source

### ISSUE THREAD

**Issue by pavel-b-novikov** [IlyaTolstihin/nsudotnet#2]
А, так вот вам зачем нужно было знать как Image биндится.

Ну и таки в данном случае использование конструкции
```C#
Foreground = (string)Application.Current.FindResource(bigCell.Symbol.ToString());
``` 
Выглядит достаточно корявым.
Вы сделайте ValueConverter лучше, который будет преобразовывать Symbol в нужную картинку. Тогда будет хорошо.

**Comment by pavel-b-novikov** [comment]
Илья, не будете отвечать на доп вопросы - останетесь с 7 баллами.

**Comment by IlyaTolstihin** [comment]
Павел, я скидывал вам репозиторий после коммита в понедельник, вы ничего не ответили.

**Comment by pavel-b-novikov** [comment]
И? У вас 2 открытых Issue, я их мониторю. ЧЯДНТ?

**Comment by IlyaTolstihin** [comment]
Я исправил привязку Image через ValueConverter, как вы сказали

**Comment by pavel-b-novikov** [comment]
Ну ладно.. и так сойдет.
